name: C CI

on:
  push:
    branches: [ next, master ]
  pull_request:
    branches: [ next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        meson: [false, true]
        os: [ubuntu-latest, ubuntu-16.04]

    runs-on: ${{ matrix.os }}
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: install & build deps
      run : |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends dpkg-dev devscripts git equivs build-essential clang
        sudo mk-build-deps --install --remove --tool 'apt-get --no-install-recommends -y' debian/control
    - name: autoreconf
      run: autoreconf -fi && mkdir build
      if: ${{ ! matrix.meson }}
    - name: configure
      run: ../configure
      working-directory: build
      if: ${{ ! matrix.meson }}
    - name: make
      run: make -j$(nproc) || (cat config.log && false)
      working-directory: build
      if: ${{ ! matrix.meson }}
    - name: meson
      run: |
        mkdir build
        cd build
        meson ..
      if: ${{ matrix.meson }}
    - name: ninja
      run: ninja
      working-directory: build
      if: ${{ matrix.meson }}
    - name: install test dependencies
      run: |
        sudo apt-get install -y cpanminus libanyevent-perl libdata-dump-perl libextutils-depends-perl libextutils-pkgconfig-perl libinline-c-perl libinline-perl libipc-run-perl libjson-xs-perl libmodule-install-perl libmouse-perl libmousex-nativetraits-perl libtest-deep-perl libtest-differences-perl libtest-exception-perl libtest-fatal-perl libtest-simple-perl libx11-xcb-perl libxcb-xtest0-dev libxml-parser-perl libxml-simple-perl libxml-tokeparser-perl perl x11-xserver-utils xauth xcb-proto xserver-xephyr xvfb
    - name: make check
      run: make check
      working-directory: build
      if: ${{ ! matrix.meson }}
    - name: ninja test
      run: ninja test
      working-directory: build
      if: ${{ matrix.meson }}
